version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    platform: linux/amd64
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pa33word!
    ports:
      - "1433:1433"
    volumes:
      - ./sqlserver-data:/var/opt/mssql 